In [2]:
import pandas as pd
orders = pd.read_csv("../data/raw/order_history.csv")

print("Shape:", orders.shape)
orders.head()

Shape: (21321, 29)

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...

In [3]:
orders.columns = orders.columns.str.lower().str.replace(" ", "_")
orders.columns

Index(['restaurant_id', 'restaurant_name', 'subzone', 'city', 'order_id',
       'order_placed_at', 'order_status', 'delivery', 'distance',
       'items_in_order', 'instructions', 'discount_construct', 'bill_subtotal',
       'packaging_charges', 'restaurant_discount_(promo)',
       'restaurant_discount_(flat_offs,_freebies_&_others)', 'gold_discount',
       'brand_pack_discount', 'total', 'rating', 'review',
       'cancellation_/_rejection_reason',
       'restaurant_compensation_(cancellation)',
       'restaurant_penalty_(rejection)', 'kpt_duration_(minutes)',
       'rider_wait_time_(minutes)', 'order_ready_marked',
       'customer_complaint_tag', 'customer_id'],
      dtype='object')

In [4]:
orders['order_placed_at'] = pd.to_datetime(orders['order_placed_at'])

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12812\2998613857.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  orders['order_placed_at'] = pd.to_datetime(orders['order_placed_at'])

In [5]:
orders.dtypes

restaurant_id                                                  int64
restaurant_name                                               object
subzone                                                       object
city                                                          object
order_id                                                       int64
order_placed_at                                       datetime64[ns]
order_status                                                  object
delivery                                                      object
distance                                                      object
items_in_order                                                object
instructions                                                  object
discount_construct                                            object
bill_subtotal                                                float64
packaging_charges                                            float64
restaurant_discount_(promo)                                  float64
restaurant_discount_(flat_offs,_freebies_&_others)           float64
gold_discount                                                float64
brand_pack_discount                                          float64
total                                                        float64
rating                                                       float64
review                                                        object
cancellation_/_rejection_reason                               object
restaurant_compensation_(cancellation)                       float64
restaurant_penalty_(rejection)                               float64
kpt_duration_(minutes)                                       float64
rider_wait_time_(minutes)                                    float64
order_ready_marked                                            object
customer_complaint_tag                                        object
customer_id                                                   object
dtype: object

In [6]:
orders['distance_km'] = (
    orders['distance']
    .str.replace('<', '', regex=False)
    .str.replace('km', '', regex=False)
    .astype(float)
)

In [7]:
orders[['items_in_order']].head()

                                      items_in_order
0  1 x Grilled Chicken Jamaican Tender, 1 x Grill...
1  1 x Peri Peri Fries, 1 x Fried Chicken Angara ...
2              1 x Bone in Peri Peri Grilled Chicken
3  1 x Fried Chicken Ghostbuster Tender, 1 x Anga...
4  1 x Peri Peri Krispers, 1 x Fried Chicken Anga...

In [8]:
orders['items_in_order'].unique()[:10]

array(['1 x Grilled Chicken Jamaican Tender, 1 x Grilled Chicken Peri Peri Tangdi',
       '1 x Peri Peri Fries, 1 x Fried Chicken Angara Tender, 1 x Grilled Chicken Angara Tender',
       '1 x Bone in Peri Peri Grilled Chicken',
       '1 x Fried Chicken Ghostbuster Tender, 1 x Angara Grilled Paneer (8 pcs)',
       '1 x Peri Peri Krispers, 1 x Fried Chicken Angara Tender',
       '1 x Grilled Chicken Jamaican Tangdi, 1 x Bone in Jamaican Grilled Chicken',
       '1 x Bone in Jamaican Grilled Chicken',
       '1 x Bone in Angara Grilled Chicken',
       '1 x Fried Chicken Angara Tender, 1 x Angara Rice',
       '1 x Grilled Chicken Peri Peri Tangdi'], dtype=object)

In [9]:
orders['item_count'] = orders['items_in_order'].str.count(' x ')
orders[['items_in_order','item_count']].head()

                                      items_in_order  item_count
0  1 x Grilled Chicken Jamaican Tender, 1 x Grill...           2
1  1 x Peri Peri Fries, 1 x Fried Chicken Angara ...           3
2              1 x Bone in Peri Peri Grilled Chicken           1
3  1 x Fried Chicken Ghostbuster Tender, 1 x Anga...           2
4  1 x Peri Peri Krispers, 1 x Fried Chicken Anga...           2

In [10]:
orders.to_csv("../data/processed/clean_orders.csv", index=False)